apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: eldakak-net-tls
spec:
    secretName: eldakak-net
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: eldakak.net
    dnsNames:
        - eldakak.net
        - www.eldakak.net
    acme:
        config:
            - http01:
                ingressClass: nginx
              domains:
                - eldakak.net
                - www.eldakak.net